Repository spectatorpublishing/Clubs-2020, pull requests merged in 2020-11, with the labels that each got.

#49 Add text input component
  client/src/components/checkbox/index.js
  client/src/components/customHooks/index.js
  client/src/components/dropdown/index.js
  client/src/components/searchTag/index.js
  client/src/components/textInput/helper.js
  client/src/components/textInput/index.js
  client/src/containers/ProfileCreation.js
Labels: Forms Team, enhancement

#57 Add filled button component
  client/src/components/filledButton/index.js
  client/src/containers/ProfileCreation.js
  client/src/theme.js
  src/components/searchTag/index.js
Labels: Forms Team, enhancement

#62 [Database] Creating DB connection
  .gitignore
  README.md
  client/README.md
  server/config/index.js
  server/models/ClubProfileModel.js
  server/models/index.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: Databases Team

#78 Db controllers
  server/controllers/clubProfileController.js
Labels: Databases Team

#63 Db schema
  server/models/ClubProfileModel.js
Labels: Databases Team

#87 getAll function return only selected fields
  server/controllers/clubProfileController.js
Labels: Databases Team

#90 Meeting frequency component
  client/src/components/frequencyTag/index.js
  client/src/containers/ProfileBoxTester.js
Labels: React Team

#96 Explore main page
  client/src/components/filters/join.js
  client/src/components/filters/shuffle.js
  client/src/components/filters/size.js
  client/src/components/filters/type.js
  client/src/containers/Explore.js
Labels: React Team

#67 Created Club Profile Page
  client/src/App.js
  client/src/components/frequencyTag/index.js
  client/src/components/profileMainContent/index.js
  client/src/components/profilePageBox/index.js
  client/src/containers/ClubProfile.js
  client/src/containers/Explore.js
  server/controllers/clubProfileController.js
  server/package-lock.json
  server/package.json
Labels: React Team

#89 Add Profile Creation Page1
  client/src/App.js
  client/src/components/checkbox/index.js
  client/src/components/contexts/index.js
  client/src/components/customHooks/index.js
  client/src/components/dropdown/index.js
  client/src/components/explorebox/index.js
  client/src/components/filledButton/index.js
  client/src/components/grayTag/container.js
  client/src/components/grayTag/index.js
  client/src/components/logout/index.js
  client/src/components/navbar/index.js
  client/src/components/profilePageBox/index.js
  client/src/components/redAsterisk/index.js
  client/src/components/searchTag/index.js
  client/src/components/textInput/helper.js
  client/src/components/textInput/index.js
  client/src/components/viewportProvider/index.js
  client/src/components/websiteTitle/index.js
  client/src/containers/Explore.js
  client/src/containers/FAQ.js
  client/src/containers/ProfileBoxTester.js
  client/src/containers/ProfileCreation/ProfileCreation1/data.js
  client/src/containers/ProfileCreation/ProfileCreation1/helpers.js
  client/src/containers/ProfileCreation/ProfileCreation1/index.js
  client/src/containers/ProfileCreation/ProfileCreation1/styles.js
  client/src/containers/ProfileCreation/ProfileCreation2.js
  client/src/containers/ProfileCreation/ProfileCreationMaster.js
  client/src/index.css
  client/src/theme.js
  src/components/logout/index.js
  src/components/websiteTitle/index.js
  src/containers/ProfileCreation/ProfileCreation1.js
  src/containers/Test.js
Labels: React Team
