Repository spectatorpublishing/Clubs-2020, pull requests merged in 2021-03, with the labels that each got.

#145 Filter Dropdowns On Explore page
  client/src/components/filters/join.js
  client/src/components/filters/size.js
  client/src/components/filters/type.js
  client/src/containers/Explore.js
Labels: Filtering team

#137 Filters db
  client/package.json
  client/src/containers/FAQ.js
  server/controllers/clubProfileController.js
  server/routes/clubProfileRoutes.js
Labels: Filtering team

#129 Search function
  server/controllers/clubProfileController.js
Labels: Filtering team

#146 Implemented Login/Logout & Signup Functionality For Login Modal
  client/src/App.js
  client/src/components/signout/index.js
  client/src/components/signup/helper.js
  client/src/components/signup/index.js
  client/src/components/tomatoButton/index.js
  client/src/containers/FirebaseApiSetUpTest/firebase/signin.jsx
  client/src/containers/Login.js
  client/src/containers/SignUp.js
Labels: User Auth Team

#147 Frontend updates
  client/src/App.js
  client/src/components/filters/join.js
  client/src/components/filters/size.js
  client/src/components/filters/type.js
  client/src/components/searchBar/index.js
  client/src/containers/ClubProfile.js
  client/src/containers/Explore.js
  client/src/containers/FAQ.js
  package.json
Labels: React Team

#126 [Databases] Updated club profile models and related functions
  server/controllers/clubProfileController.js
  server/models/ClubAccountModel.js
  server/models/ClubProfileModel.js
  server/routes/clubProfileRoutes.js
Labels: Databases Team

#157 Merge Frontend Bug Fixes/Updates to Master
  client/src/components/explorebox/index.js
  client/src/components/profileMainContent/index.js
  client/src/components/socialTagsBox/index.js
  client/src/containers/ClubProfile.js
  client/src/containers/Explore.js
Labels: React Team

#153 Added remember me functionality
  .idea/.gitignore
  .idea/Clubs-2020.iml
  .idea/modules.xml
  .idea/vcs.xml
  client/build/asset-manifest.json
  client/build/index.html
  client/build/precache-manifest.de1e99054e6d98ecf009e4d745e711a5.js
  client/build/service-worker.js
  client/build/static/css/main.0f776032.chunk.css
  client/build/static/css/main.0f776032.chunk.css.map
  client/build/static/js/2.3080a0ec.chunk.js
  client/build/static/js/2.3080a0ec.chunk.js.LICENSE.txt
  client/build/static/js/2.3080a0ec.chunk.js.map
  client/build/static/js/main.f4f6bc33.chunk.js
  client/build/static/js/main.f4f6bc33.chunk.js.map
  client/build/static/js/runtime-main.a796cb08.js
  client/build/static/js/runtime-main.a796cb08.js.map
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/checkbox/index.js
  client/src/components/signup/index.js
  client/src/containers/FirebaseApiSetUpTest/firebase/rememberMe.jsx
  package.json
  server/package-lock.json
Labels: User Auth Team, enhancement

#154 Reset Password feature
  client/src/App.js
  client/src/components/signup/index.js
  client/src/containers/ConfirmPasswordReset.js
  client/src/containers/FindPassword.js
Labels: User Auth Team, enhancement
